/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject.restaurant;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.table.DefaultTableModel;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;

/**
 *
 * @author mike
 */
public class Favorite extends javax.swing.JFrame {

    /**
     * Creates new form Appetizer
     */
    public Favorite() {
        initComponents();
        nonactive();
    }
    public void nonactive(){
        sidebar.setVisible(false);
        sidebar.setEnabled(false);
        jLabel2.setVisible(false);
        jLabel2.setEnabled(false);
        Favorite.setVisible(true);
        Favorite.setVisible(true);
    }
    public void active() {
        sidebar.setVisible(true);
        sidebar.setEnabled(true);
        jLabel2.setVisible(true);
        jLabel2.setEnabled(true);
        Favorite.setVisible(false);
        Favorite.setVisible(false);
        
    }
    
    DefaultTableModel model;
    String item;
    int price;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        NewOrder = new javax.swing.JButton();
        SalmonSashimi = new javax.swing.JRadioButton();
        Gyoza = new javax.swing.JRadioButton();
        garlicsalmon = new javax.swing.JRadioButton();
        SpicyUnagi = new javax.swing.JRadioButton();
        confirmButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        sbutton = new javax.swing.JLabel();
        sidebar = new javax.swing.JLabel();
        Favorite = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(235, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(153, 153, 153))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(637, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(52, 52, 52))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 1122));
        setPreferredSize(new java.awt.Dimension(1024, 1122));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel3.setMaximumSize(new java.awt.Dimension(1024, 1122));
        jPanel3.setLayout(null);

        NewOrder.setBorder(null);
        NewOrder.setContentAreaFilled(false);
        NewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewOrderActionPerformed(evt);
            }
        });
        jPanel3.add(NewOrder);
        NewOrder.setBounds(370, 600, 120, 100);
        jPanel3.add(SalmonSashimi);
        SalmonSashimi.setBounds(700, 240, 30, 23);

        Gyoza.setContentAreaFilled(false);
        jPanel3.add(Gyoza);
        Gyoza.setBounds(490, 230, 30, 23);

        garlicsalmon.setBackground(new java.awt.Color(255, 253, 231));
        garlicsalmon.setContentAreaFilled(false);
        jPanel3.add(garlicsalmon);
        garlicsalmon.setBounds(250, 230, 30, 23);

        SpicyUnagi.setContentAreaFilled(false);
        SpicyUnagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpicyUnagiActionPerformed(evt);
            }
        });
        jPanel3.add(SpicyUnagi);
        SpicyUnagi.setBounds(880, 240, 30, 23);

        confirmButton.setBackground(new java.awt.Color(255, 253, 231));
        confirmButton.setBorder(null);
        confirmButton.setContentAreaFilled(false);
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        jPanel3.add(confirmButton);
        confirmButton.setBounds(870, 640, 100, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Item", "Price"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(530, 610, 300, 100);

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel2);
        jLabel2.setBounds(120, 50, 900, 720);

        sbutton.setBackground(new java.awt.Color(255, 225, 198));
        sbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sbuttonMouseEntered(evt);
            }
        });
        jPanel3.add(sbutton);
        sbutton.setBounds(20, 60, 60, 50);

        sidebar.setIcon(new javax.swing.ImageIcon("/Users/mike/Downloads/Group 241.png")); // NOI18N
        sidebar.setText("jLabel4");
        jPanel3.add(sidebar);
        sidebar.setBounds(0, -510, 130, 1830);

        Favorite.setIcon(new javax.swing.ImageIcon("/Users/mike/Downloads/Favorite.png")); // NOI18N
        Favorite.setPreferredSize(new java.awt.Dimension(600, 600));
        Favorite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FavoriteMouseClicked(evt);
            }
        });
        jPanel3.add(Favorite);
        Favorite.setBounds(0, -110, 1024, 990);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(264, 264, 264))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FavoriteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FavoriteMouseClicked
   
    }//GEN-LAST:event_FavoriteMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        nonactive();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void sbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sbuttonMouseEntered
    active();
    }//GEN-LAST:event_sbuttonMouseEntered

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
     if(garlicsalmon.isSelected() == true)
     { 
         item = " Garlic Salmon Roll ";
         price = 45000;
         
     } else if (Gyoza.isSelected()== true)
     {
         item = " Gyoza ";
         price= 30000;
         
     } else if (SalmonSashimi.isSelected() == true) 
     {
         item = " Salmon Sashimi ";
         price = 75000;
         
     } else if (SpicyUnagi.isSelected() == true) 
     {
         item = " Spicy Unagi";
         price = 35000;
         
     }
         
     
     model = (DefaultTableModel)jTable1.getModel();
     model.addRow(new Object[]
     {
         item, price
     });
     
     try {
        String url = "jdbc:mysql://localhost:8889/Restaurant";
        String userid = "root";
        String password = "root";
        String sql = "INSERT INTO `ListOrder` ( `Item`, `Price`) VALUES (?,?)";
        
        
        
        Connection connection = DriverManager.getConnection(url, userid, password);
        
       
        
        PreparedStatement preparedStmt = connection.prepareStatement(sql);
        jTable1.getModel();
        preparedStmt.execute();
        
       
        
        
        
        
        
        
        
        
        
        
        
        } catch(SQLException ex) {
        Logger.getLogger(Favorite.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void SpicyUnagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpicyUnagiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SpicyUnagiActionPerformed

    private void NewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewOrderActionPerformed
        // TODO add your handling code here:
    jTable1.setModel(new DefaultTableModel(null, new String[]{"item","price"} ));
    }//GEN-LAST:event_NewOrderActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
     try {
            String url = "jdbc:mysql://localhost:8889/Restaurant";
            String userid = "root";
            String password = "root";
            String sql = "SELECT * FROM ListOrder";
            
            Connection connection = DriverManager.getConnection(url, userid, password);
            java.sql.Statement stmt = connection.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            ResultSetMetaData md = rs.getMetaData();
            int columns = md.getColumnCount();
            DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
            tm.setColumnCount(0);
            for(int i = 1; i<=columns; i++) {
                tm.addColumn(md.getColumnName(i));
            }
            tm.setRowCount(0);
            while(rs.next()) {
                String[] a = new String[columns];
                for(int i =0; i<columns;i++); {
                    int i = 0;
                a[i] = rs.getString(i+1);
            }
                tm.addRow(a);
            }
            rs.close();
            stmt.close();
     }  catch(SQLException ex) {
            Logger.getLogger(Favorite.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Favorite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Favorite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Favorite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Favorite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Favorite().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Favorite;
    private javax.swing.JRadioButton Gyoza;
    private javax.swing.JButton NewOrder;
    private javax.swing.JRadioButton SalmonSashimi;
    private javax.swing.JRadioButton SpicyUnagi;
    private javax.swing.JButton confirmButton;
    private javax.swing.JRadioButton garlicsalmon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel sbutton;
    private javax.swing.JLabel sidebar;
    // End of variables declaration//GEN-END:variables
}
